/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

void calculate_prog_1(char *host, int x, char sinal, int y)
{
    CLIENT *clnt;
    int  *result; 
    numbers args; 

#ifndef DEBUG
    clnt = clnt_create(host, ADD_PROG, ADD_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif 

    args.a = x;
    args.b = y;
    
    
    switch (sinal) {
        case '+':
            result = add_1(&args, clnt);
            break;
        case '-':
            result = sub_1(&args, clnt);
            break;
        case 'X':
            result = mul_1(&args, clnt);
            break;
        case '/':
            result = div_1(&args, clnt);
            break;
        default:
   	    break;
    }

    if (result == (int *) NULL) {
        clnt_perror(clnt, "A chamada falhou");
        exit(1);
    }

    printf("%d %c %d = %d\n", x, sinal, y, *result);

#ifndef DEBUG
    clnt_destroy(clnt);
#endif   /* DEBUG */
}

int main(int argc, char *argv[])
{
    char *host;
    int num1, num2;
    char operador;

    //./client <host> <num1> <operador> <num2>
    if (argc < 5) {
        printf("Uso: %s <host_servidor> <numero1> <operador> <numero2>\n", argv[0]);
        exit(1);
    }

    host = argv[1];
    num1 = atoi(argv[2]);      
    operador = argv[3][0];   
    num2 = atoi(argv[4]);

    calculate_prog_1(host, num1, operador, num2);
    
    exit(0);
}
